language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      os: linux
      sudo: required
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --user --upgrade pip || sudo pip3 --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install --user -r requirements.txt

script: python3 tests.py || python tests.py
